Django4TW/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('TODOlist.urls')),
]

TODOlist/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^list/all$', views.ToDoListView.as_view(), name='all-lists'),
    url(r'^list/add/$', views.ToDoListCreateView.as_view(), name='add-list'),
    url(r'^list/(?P<pk>\d+)/task/add/$', views.TaskCreateView.as_view(), name='add-task'),
    url(r'^list/task/(?P<pk>\d+)/edit/$', views.TaskUpdateView.as_view(), name='update-task'),
    url(r'^list/(?P<pk>\d+)/edit/$', views.ToDoListUpdateView.as_view(), name='update-list'),
    url(r'^list/(?P<pk>\d+)/task/delete/$', views.TaskDeleteView.as_view(), name='delete-task'),
    url(r'^list/(?P<pk>\d+)/delete/$', views.ToDoListDeleteView.as_view(), name='delete-list'),
]

TODOlist/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.timezone import now

STATUS = (
    (1, "Completed"),
    (0, "Not Completed")
)


# Create your models here.
class ToDoList(models.Model):
    name = models.TextField(default='', blank=True, null=True, verbose_name='Name')
    last_update = models.DateField(null=False, default=now, verbose_name='Last update')

    def __unicode__(self):
        return self.name


class Task(models.Model):
    name = models.TextField(default='', blank=True, null=True, verbose_name='Name')
    todolist = models.ForeignKey(ToDoList, null=True, blank=True, verbose_name='TODOlist', on_delete=models.CASCADE)
    completed = models.BooleanField(default=False, choices=STATUS, verbose_name='Is it finished?')
    text = models.TextField(default='', blank=True, null=True, verbose_name='Task')
    last_update = models.DateField(null=True, default=now, verbose_name='Last update')

    def __unicode__(self):
        return self.text

TODOlist/forms.py
from django import forms
from .models import Task, ToDoList


class TaskCreateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'cols': 20, 'rows': 5}),
        }


class ToDoListCreateForm(forms.ModelForm):
    class Meta:
        model = ToDoList
        fields = ['name']


class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['text', 'completed']
        widgets = {
            'text': forms.Textarea(attrs={'cols': 20, 'rows': 5}),
            'completed': forms.RadioSelect
        }

TODOlist/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, TemplateView, DetailView
from django.core.urlresolvers import reverse_lazy
from django.utils.timezone import now
from django.http import HttpResponse

from .models import Task, ToDoList
from .forms import TaskCreateForm, ToDoListCreateForm, TaskUpdateForm


# Create your views here.
class TaskCreateView(CreateView):
    model = Task
    form_class = TaskCreateForm
    template_name = 'add_form.html'
    success_url = reverse_lazy("all-lists")

    def get_context_data(self, **kwargs):
        context = super(TaskCreateView, self).get_context_data(**kwargs)
        context['task_create'] = True
        return context

    def form_valid(self, form, **kwargs):
        context = super(TaskCreateView, self).form_valid(form, **kwargs)
        todolist = ToDoList.objects.get(pk=self.kwargs['pk'])
        todolist.last_update = now()
        todolist.save()
        form.instance.todolist = todolist
        form.save()
        return context


class ToDoListCreateView(CreateView):
    model = ToDoList
    form_class = ToDoListCreateForm
    template_name = 'add_form.html'
    success_url = reverse_lazy("all-lists")

    def get_context_data(self, **kwargs):
        context = super(ToDoListCreateView, self).get_context_data(**kwargs)
        context['todolist_create'] = True
        return context


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("all-lists")


class ToDoListDeleteView(DeleteView):
    model = ToDoList
    success_url = reverse_lazy("all-lists")


class ToDoListUpdateView(UpdateView):
    model = ToDoList
    form_class = ToDoListCreateForm
    template_name = 'add_form.html'
    success_url = reverse_lazy("all-lists")

    def get_context_data(self, **kwargs):
        context = super(ToDoListUpdateView, self).get_context_data(**kwargs)
        context['todolist_update'] = True
        return context

    def form_valid(self, form, **kwargs):
        context = super(ToDoListUpdateView, self).form_valid(form, **kwargs)
        form.instance.last_update = now()
        form.save()
        return context


class ToDoListView(ListView):
    model = ToDoList
    template_name = 'show_lists.html'

    def get_context_data(self, **kwargs):
        context = super(ToDoListView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        return self.model.objects.all()


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        return context


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskUpdateForm
    template_name = 'add_form.html'
    success_url = reverse_lazy("all-lists")

    def get_context_data(self, **kwargs):
        context = super(TaskUpdateView, self).get_context_data(**kwargs)
        context['task_update'] = True
        return context

    def form_valid(self, form, **kwargs):
        context = super(TaskUpdateView, self).form_valid(form, **kwargs)
        todolist = ToDoList.objects.get(pk=form.instance.todolist.pk)
        todolist.last_update = now()
        todolist.save()
        form.instance.last_update = now()
        form.save()
        return context

templates/TODOlist/task_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

templates/TODOlist/todolist_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

templates/add_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block content %}



<div class="container">
    <div class="row">
        <form id="product-form" class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{form|bootstrap}}

            <div class="form-group text-right">

                {% if task_create %}
                <button class="btn btn-info" type="submit" value="save" name="save" >Create Task</button>
                {% elif task_update %}
                <button class="btn btn-info" type="submit" value="save" name="save" >Update Task</button>
                {% elif todolist_create %}
                <button class="btn btn-info" type="submit" value="save" name="save" >Create ToDoList</button>
                {% elif todolist_update %}
                <button class="btn btn-info" type="submit" value="save" name="save" >Update ToDoList</button>
                {% endif %}
            </div>

        </form>
    </div>
</div>
{% endblock %}html>

templates/add_task.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block content %}



<div class="container">
    <div class="row">
        <form id="product-form" class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{form|bootstrap}}

            <div class="form-group text-right">
                <button class="btn btn-info" type="submit" value="save" name="save" >Create Task</button>
            </div>

        </form>
    </div>
</div>
{% endblock %}html>

templates/details_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover" >
                <thead>
                <tr>
                    <th>Name</th>
                </tr>
                </thead>
                <tbody>

                    {% for task in object.task_set.all %}
                        <tr>
                            <td>
                                {{ task.name }}
    <a href="{% url 'edit-task' task.pk %}" class="btn-link">
    <span class="glyphicon glyphicon-pencil"></span></a>
                            </td>
                        </tr>
                    {% endfor %}


                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load i18n %}
{% block content %}

    <div class="row">
        <div class="col-sm-12">

            <h1>Django Project</h1>
            <h2>Laco Smokowski</h2>
            <p>
                Przygotować listę Todo tak by można było:
		-dodawać nowe zadania<br>
		-odznaczać zrealizowane zadania<br>
<br>
	Co musi być w projekcie:<br>
		-modele z automatycznie dodawanymi datami tworzenia i aktualizacji<br>
		-panel administratora (django admin)<br>
		-django template<br>
            </p>
        </div>
    </div>

{% endblock %}

templates/show_lists.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover" >
                <thead>
                <tr>
                </tr>
                </thead>
                <tbody>
                    <tr>
                    {% for list in todolist_list %}
                                <td>
                                <h1>{{ list.name }}</h1>
                                <a href="{% url 'add-task' list.pk %}" class="btn-link">
                                    <span class="glyphicon glyphicon-plus"></span></a>
                                    <a href="{% url 'update-list' list.pk %}" class="btn-link">
                            <span class="glyphicon glyphicon-pencil"></span></a>
                                    <a href="{% url 'delete-list' list.pk %}" class="btn-link">
                                    <span class="glyphicon glyphicon-remove"></span></a><br/>
                                    {{list.last_update  }}
                            </td>

                {% for task in list.task_set.all %}
                    <tr>
                    <td>
                        {{  task.text }} <br/>Status:
                        {{ task.get_completed_display }}
                        <a href="{% url 'update-task' task.pk %}" class="btn-link">
                            <span class="glyphicon glyphicon-pencil"></span></a>
                        <a href="{% url 'delete-task' task.pk %}" class="btn-link">
                                    <span class="glyphicon glyphicon-remove"></span></a><br/>
                        {{task.last_update  }}

                    </td>
                    </tr>
                     {% endfor %}
                    </tr>
                    {% endfor %}


                </tbody>
            </table>
        </div>
    </div>

{% endblock %}